version: "3"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: games
    ports:
      - 3306:3306

    volumes:
      - ./prisma:/docker-entrypoint-initdb.d
