name: Push DB docker image to Dockerhub

on:
    schedule:
      # sets the action to run daily. You can modify this to run the action more or less frequently
      - cron: "0 0 * * *"

jobs:
  push_to_registry:
    name: Push DB to Dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Dokcerhub
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
      
      - name: Extract metadata (tags, labels) from Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/game-project-back:latest

      - name: Build and push to Dockerhub
        uses: docker/build-push-action@v3
        with:  
          context: ./prisma
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
